site_name: ProjectLens
site_description: A tool for collecting and analyzing project files for LLM optimization
site_url: https://cmcouto-silva.github.io/projectlens/
repo_url: https://github.com/cmcouto-silva/projectlens
repo_name: cmcouto-silva/projectlens

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.tabs.link
    - toc.follow
  icon:
    repo: fontawesome/brands/github
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - def_list
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: google
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Usage:
    - CLI: usage/cli-usage.md
    - Python API: usage/python-api.md
    - Configuration: usage/configuration.md
    # - Advanced Usage: usage/advanced-usage.md
  # - Guides:
  #   - Use Cases: guides/use-cases.md
  #   - LLM Integration: guides/llm-integration.md
  #   - Best Practices: guides/best-practices.md
  # - API Reference: 
  #   - Overview: api/overview.md
  #   - ProjectLens: api/projectlens.md
  #   - ProjectMetadata: api/metadata.md
  #   - Utilities: api/utils.md
  # - Contributing: contributing.md
  # - Changelog: changelog.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cmcouto-silva
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/projectlens/
  version:
    provider: mike
    
copyright: Copyright &copy; 2024 Cainã Max Couto da Silva